### ISSUE TITLE
No imu data found, is imu data necessary for A-LOAM?

### ISSUE THREAD

**Issue by eyes366** [HKUST-Aerial-Robotics/A-LOAM#1]
No imu data found in code, is imu data necessary for A-LOAM?

**Comment by qintonguav** [comment]
IMU is not used in this code.

**Comment by mhaboali** [comment]
Hi @qintonguav 

I'm interested in adding the GPS and the IMU readings to your algorithm, and I'm willing to collaborate with you to achieve that.

Could you give me some guidance and I'll be ready to start directly the development part?

Thanks!
