### ISSUE TITLE
ground pose frame and laser points frame

### ISSUE THREAD

**Issue by narutojxl** [HKUST-Aerial-Robotics/A-LOAM#12]
Hi @shaozu , thanks for your share. According to kitti_development_kit/readme.txt,  GT pose is left camera(Z-front, X-right, Y-down) in left_camera_0th(world) pose. when convert GT pose into loam's camera_init frame(Z-front, X-left, Y-up), use [R_transform << 0, 0, 1, -1, 0, 0, 0, -1, 0;](https://github.com/HKUST-Aerial-Robotics/A-LOAM/blob/e51f88c12b483ce42dfa219783712c7234dc8c08/src/kittiHelper.cpp#L79). I think `R_camInit_world = Rz(-pi),  p_camInit =  R_camInit_world * GT_pose,  should be R_transform << -1, 0, 0, 0, -1, 0, 0, 0, 1 `?

When publish  "/velodyne_points" to loam, each points is in camera_init loam's world frame, why not is velodyne frame? 

Thanks in advance!

**Comment by LongruiDong** [comment]
Hi ,
I am also confusing about that, do you understand now?
thanks !
