### ISSUE TITLE
Question about Kitti data.

### ISSUE THREAD

**Issue by Gatsby23** [HKUST-Aerial-Robotics/A-LOAM#14]
The results from rviz I can get is this:
![A-LOAM-RVIZ](https://user-images.githubusercontent.com/18000675/63732571-73d5dd00-c8a7-11e9-8529-77761f2e4d4a.png)
and I have already select after_maped topic. Is there anything wrong?
I also confused that I can't find my point cloud image and i have select the point cloud topic too? I realy want to know how to recurring the effect like this ?
![image](https://user-images.githubusercontent.com/18000675/63732644-cb744880-c8a7-11e9-8f3f-872b1000d8c8.png)
I really need your help, Is there anything wrong, could you please give me some advice ? Thanks!

**Comment by LongruiDong** [comment]
> The results from rviz I can get is this:
> ![A-LOAM-RVIZ](https://user-images.githubusercontent.com/18000675/63732571-73d5dd00-c8a7-11e9-8529-77761f2e4d4a.png)
> and I have already select after_maped topic. Is there anything wrong?
> I also confused that I can't find my point cloud image and i have select the point cloud topic too? I realy want to know how to recurring the effect like this ?
> ![image](https://user-images.githubusercontent.com/18000675/63732644-cb744880-c8a7-11e9-8f3f-872b1000d8c8.png)
> I really need your help, Is there anything wrong, could you please give me some advice ? Thanks!

you can select "/image_left" in the **image** _topic_ , then image window will show image sequences;

However I  am also confusing about how to display that _moving red car_ in above example picture, anyone knows?

**Comment by Gatsby23** [comment]
> > The results from rviz I can get is this:
> > ![A-LOAM-RVIZ](https://user-images.githubusercontent.com/18000675/63732571-73d5dd00-c8a7-11e9-8529-77761f2e4d4a.png)
> > and I have already select after_maped topic. Is there anything wrong?
> > I also confused that I can't find my point cloud image and i have select the point cloud topic too? I realy want to know how to recurring the effect like this ?
> > ![image](https://user-images.githubusercontent.com/18000675/63732644-cb744880-c8a7-11e9-8f3f-872b1000d8c8.png)
> > I really need your help, Is there anything wrong, could you please give me some advice ? Thanks!
> 
> you can select "/image_left" in the **image** _topic_ , then image window will show image sequences;
> 
> However I am also confusing about how to display that _moving red car_ in above example picture, anyone knows?

Thank you for your replay. I have already know how to view the image sequences. The problem is that I thought the odometry path is too low to believe. Another thing is why the colorful points doesn't show anymore ?

**Comment by zhu-bingo** [comment]
can you tell me how to run a-loam with kitti odometry dataset

**Comment by dhananjaisharma10** [comment]
> The results from rviz I can get is this:
> ![A-LOAM-RVIZ](https://user-images.githubusercontent.com/18000675/63732571-73d5dd00-c8a7-11e9-8529-77761f2e4d4a.png)
> and I have already select after_maped topic. Is there anything wrong?
> I also confused that I can't find my point cloud image and i have select the point cloud topic too? I realy want to know how to recurring the effect like this ?
> ![image](https://user-images.githubusercontent.com/18000675/63732644-cb744880-c8a7-11e9-8f3f-872b1000d8c8.png)
> I really need your help, Is there anything wrong, could you please give me some advice ? Thanks!

Hi! Could you please tell me how to run A-LOAM on the KITTI odometry dataset in a bit detail. I followed the README instructions but couldn't get it to run. Please let me know. Thanks!

**Comment by mhaboali** [comment]
For the future debuggers, 

Try to debug a little bit the values of the paths inside kittihelper.cpp node. After fixing those paths you'll be able to run the example with KITTI odometry data exactly as it's shown in readme file.

Muhammad,
Thanks

**Comment by Gatsby23** [comment]
> For the future debuggers,
> 
> Try to debug a little bit the values of the paths inside kittihelper.cpp node. After fixing those paths you'll be able to run the example with KITTI odometry data exactly as it's shown in readme file.
> 
> Muhammad,
> Thanks

OK, Thank you a lot

**Comment by Juuustin** [comment]
> For the future debuggers,
> 
> Try to debug a little bit the values of the paths inside kittihelper.cpp node. After fixing those paths you'll be able to run the example with KITTI odometry data exactly as it's shown in readme file.
> 
> Muhammad,
> Thanks

Could you write more for debugging?

**Comment by mhaboali** [comment]
Open the kittihelper.cpp file and check the paths for poses, images, and lidar folders. Let me know if it's still unclear.

Thanks,
Mohammed
