### ISSUE TITLE
No point cloud, only trajectory result output in rviz.

### ISSUE THREAD

**Issue by ZhangZh3ng** [HKUST-Aerial-Robotics/A-LOAM#45]
I got the following result  on my pc:
![2021-11-10 14-40-25 的屏幕截图](https://user-images.githubusercontent.com/63040423/141063013-df76d64e-60ab-4b39-b445-8848cff46bb7.png)
It seems the author's demo contains more information, such as point cloud:
![image](https://user-images.githubusercontent.com/63040423/141064075-9c1bd5c6-fe6f-4543-a87b-eac190282342.png)

what should i do to display these information in rviz window?

**Comment by cybaol** [comment]
Hi bro, I also encountered the same problem, how did you solve it ?

**Comment by chj0728** [comment]
> Hi bro, I also encountered the same problem, how did you solve it ?
 Delete the  "/" of "/ camera_init" in cpp file

**Comment by dwindy** [comment]
> > Hi bro, I also encountered the same problem, how did you solve it ?
> > Delete the  "/" of "/ camera_init" in cpp file

Sry, which cpp file you mean?
the kittihelper.cpp?

**Comment by chj0728** [comment]
> > > Hi bro, I also encountered the same problem, how did you solve it ?
> > > Delete the  "/" of "/ camera_init" in cpp file
> 
> Sry, which cpp file you mean? the kittihelper.cpp?

yep，also including laserMapping.cpp,laserOdometry.cpp,scanRegistration.cpp
